# 02 — Party audit

Inspect the party metadata table and find which parties (by candidate count) still don't have curated metadata.

Upstream:
```
python -m src.clean.clean_eci_2024
python -m src.metadata.build_party_metadata
```

In [2]:
import sys
sys.path.insert(0, "..")

from src import data_io

party_meta = data_io.load_party_metadata()
party_meta.shape

(746, 6)

In [3]:
party_meta.head(20)

,party,candidate_count,party_type,alliance_2024,ideology,region
0,IND,3921,independent,OTHER,independent,local
1,NOTA,542,nota,NONE,none,none
2,BSP,488,national,OTHER,bahujan_social_justice,uttar_pradesh
3,BJP,440,national,NDA,centre-right,national
4,INC,328,national,INDIA,centre-left,national
5,SUCI,150,unknown,OTHER,unknown,unknown
6,PPID,79,unknown,OTHER,unknown,unknown
7,SP,71,regional,INDIA,socialist,uttar_pradesh
8,CPI(M),52,national,INDIA,far-left,national
9,AITC,48,regional,INDIA,centre,west_bengal
10,BHRJWNKP,41,unknown,OTHER,unknown,unknown
11,BSCP,40,unknown,OTHER,unknown,unknown
12,NTK,40,unknown,OTHER,unknown,unknown
13,APoI,38,unknown,OTHER,unknown,unknown
14,VBA,38,unknown,OTHER,unknown,unknown
15,ADMK,36,unknown,OTHER,unknown,unknown
16,AKBRPRVP,36,unknown,OTHER,unknown,unknown
17,RTORP,33,unknown,OTHER,unknown,unknown
18,AIFB,32,unknown,OTHER,unknown,unknown
19,CPI,30,national,INDIA,far-left,national

In [4]:
party_meta["alliance_2024"].value_counts()

alliance_2024
OTHER    716
INDIA     16
NDA       13
NONE       1
Name: count, dtype: int64

In [5]:
(
    party_meta[party_meta["party_type"] == "unknown"]
    .sort_values("candidate_count", ascending=False)
    .head(20)
)

         party  candidate_count party_type alliance_2024 ideology   region
5         SUCI              150    unknown         OTHER  unknown  unknown
6         PPID               79    unknown         OTHER  unknown  unknown
10    BHRJWNKP               41    unknown         OTHER  unknown  unknown
12         NTK               40    unknown         OTHER  unknown  unknown
11        BSCP               40    unknown         OTHER  unknown  unknown
13        APoI               38    unknown         OTHER  unknown  unknown
14         VBA               38    unknown         OTHER  unknown  unknown
15        ADMK               36    unknown         OTHER  unknown  unknown
16    AKBRPRVP               36    unknown         OTHER  unknown  unknown
17       RTORP               33    unknown         OTHER  unknown  unknown
18        AIFB               32    unknown         OTHER  unknown  unknown
20        BMUP               28    unknown         OTHER  unknown  unknown
21         KRS               28    unknown         OTHER  unknown  unknown
22        PPOI               26    unknown         OTHER  unknown  unknown
23       ASPKR               26    unknown         OTHER  unknown  unknown
26         GGP               23    unknown         OTHER  unknown  unknown
27       SRPSP               23    unknown         OTHER  unknown  unknown
29      RPI(A)               22    unknown         OTHER  unknown  unknown
31         SAP               22    unknown         OTHER  unknown  unknown
28  BHRTADVSIP               22    unknown         OTHER  unknown  unknown